export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAILURE = "ADD_PRODUCT_TO_CART_FAILURE";
export const REMOVE_PRODUCT_FROM_CART_REQUEST = "REMOVE_PRODUCT_FROM_CART_REQUEST";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_TO_CART";

//alert
export const SHOW_SUCCESS_ALERT_ADD = "SHOW_SUCCESS_ALERT_ADD";
export const HIDE_SUCCESS_ALERT_ADD = "HIDE_SUCCESS_ALERT_ADD";
export const SHOW_SUCCESS_ALERT_REMOVE = "SHOW_SUCCESS_ALERT_REMOVE";
export const HIDE_SUCCESS_ALERT_REMOVE = "HIDE_SUCCESS_ALERT_REMOVE";