export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const CREATE_ORDER_SHOW_ALERT = "CREATE_ORDER_SHOW_ALERT";
export const CREATE_ORDER_HIDE_ALERT = "CREATE_ORDER_HIDE_ALERT";