export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGIN_ERROR_ALERT_SHOW = "LOGIN_ERROR_ALERT";
export const LOGIN_ERROR_ALERT_HIDE = "LOGIN_ERROR_ALERT_HIDE";
export const LOGIN_SUCCESS_ALERT_SHOW = "LOGIN_SUCCESS_ALERT_SHOW";
export const LOGIN_SUCCESS_ALERT_HIDE = "LOGIN_SUCCESS_ALERT_HIDE";