export const ADD_PRODUCT_TO_FAVORITE_REQUEST = "ADD_PRODUCT_TO_FAVORITE_REQUEST";
export const ADD_PRODUCT_TO_FAVORITE_SUCCESS = "ADD_PRODUCT_TO_FAVORITE_SUCCESS";
export const ADD_PRODUCT_TO_FAVORITE_FAILURE = "ADD_PRODUCT_TO_FAVORITE_FAILURE";
export const REMOVE_PRODUCT_FROM_FAVORITE_REQUEST = "REMOVE_PRODUCT_FROM_FAVORITE_REQUEST";
export const REMOVE_PRODUCT_FROM_FAVORITE = "REMOVE_PRODUCT_FROM_FAVORITE";

//alert
export const SHOW_ALERT_ADD_TO_FAVORITE = "SHOW_ALERT_ADD_TO_FAVORITE";
export const HIDE_ALERT_ADD_TO_FAVORITE = "HIDE_ALERT_ADD_TO_FAVORITE";
export const SHOW_ALERT_REMOVE_FROM_FAVORITE = "SHOW_ALERT_REMOVE_FROM_FAVORITE";
export const HIDE_ALERT_REMOVE_FROM_FAVORITE = "HIDE_ALERT_REMOVE_FROM_FAVORITE";