export const CHANGE_TO_LINE_REQUEST = "CHANGE_TO_LINE_REQUEST";
export const CHANGE_TO_LINE = "CHANGE_TO_LINE";

export const CHANGE_TO_GRID_REQUEST = "CHANGE_TO_GRID_REQUEST";
export const CHANGE_TO_GRID = "CHANGE_TO_GRID";