export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//alerts

export const SHOW_ERROR_REGISTER = "SHOW_ERROR_REGISTER";
export const HIDE_ERROR_REGISTER = "HIDE_ERROR_REGISTER";